"""Build a composite from a row specification, and report whether it fits.

Every composite in this manuscript follows the same rules, so they are written
once here instead of being restated in each figN_assemble.tex by hand:

  * a panel is placed at exactly the width it was drawn at, never scaled. Every
    panel in figures 1 to 5 bottoms out at 5.0 to 5.6 pt type, so a placement
    scale below 1.0 would drop it under the 5 pt Nature Methods floor.
  * one gutter value per figure; rows that cannot fill 183 mm at that gutter are
    centred rather than having their gutter stretched.
  * 2.6 mm between rows, which is what the 8 pt panel letter occupies.
  * panel letters are lowercase bold 8 pt, 2.4 mm above their row's top edge.

Usage:
    python compose.py <figure-dir> <out-stem> a,b c,d e,f       # rows of stems

Stems are the panel letters; the directory's panel files are matched by their
`figNx_` prefix. Prints the page envelope and fails if the stacked height
exceeds the manuscript's usable height.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import check_panels as C  # noqa: E402

PAGE_MM = C.PAGE_MM
GUTTER_MM = 4.5
ROW_GAP_MM = C.ROW_GAP_MM
LETTER_MM = 2.4
TOP_MM = 200.0

TEMPLATE = r"""%% Generated by compose.py; edit the row spec, not this file.
%% %(note)s
\documentclass[tikz,border=1mm]{standalone}
\usepackage{graphicx}
\input{../nm_fonts.tex}
\begin{document}
\begin{tikzpicture}[x=1mm,y=1mm]
  \useasboundingbox (0,%(bottom).1f) rectangle (183,%(top).1f);
%(nodes)s
  \tikzset{plab/.style={font=\fontsize{8}{9}\selectfont\bfseries,anchor=north west,inner sep=0}}
%(labels)s
\end{tikzpicture}
\end{document}
"""


def panels_for(figure_dir: Path) -> dict[str, tuple[str, float, float]]:
    """letter -> (stem, w_mm, h_mm) for the figure whose spec matches this dir."""
    for spec in C.SPECS.values():
        if spec["dir"] == figure_dir.name:
            out = {}
            for stem, w, h in spec["panels"].values():
                letter = stem[len(figure_dir.name)]
                out[letter] = (stem, w, h)
            return out
    raise SystemExit(f"no panel spec for {figure_dir.name}")


def build(figure_dir: Path, out_stem: str, rows: list[list[str]]) -> float:
    table = panels_for(figure_dir)
    nodes, labels = [], []
    y = TOP_MM
    for row in rows:
        widths = [table[c][1] for c in row]
        used = sum(widths) + GUTTER_MM * (len(row) - 1)
        if used > PAGE_MM + 1e-6:
            raise SystemExit(
                f"row [{' '.join(row)}] is {used:.1f} mm wide, over the "
                f"{PAGE_MM:.0f} mm page. These panels cannot share a row.")
        x = (PAGE_MM - used) / 2.0
        for letter in row:
            stem, w, _ = table[letter]
            nodes.append(f"  \\node[anchor=north west,inner sep=0] at "
                         f"({x:.2f},{y:.2f}) {{\\includegraphics[width={w}mm]{{{stem}.pdf}}}};")
            labels.append(f"  \\node[plab] at ({x:.2f},{y + LETTER_MM:.2f}) {{{letter}}};")
            x += w + GUTTER_MM
        y -= max(table[c][2] for c in row) + ROW_GAP_MM
    height = TOP_MM + LETTER_MM + 0.2 - (y + ROW_GAP_MM)
    bottom = y + ROW_GAP_MM
    budget = C.HEIGHT_BUDGET_MM[C.PRINTED_OF_DIR[figure_dir.name]]
    note = (f"{len(rows)} rows, {height:.1f} mm tall, budget {budget:.1f} mm "
            f"(printed Figure {C.PRINTED_OF_DIR[figure_dir.name]}): "
            + ("FITS" if height <= budget else "DOES NOT FIT"))
    tex = TEMPLATE % {"note": note, "bottom": bottom, "top": TOP_MM + LETTER_MM + 0.2,
                      "nodes": "\n".join(nodes), "labels": "\n".join(labels)}
    path = figure_dir / f"{out_stem}.tex"
    path.write_text(tex)
    subprocess.run(["lualatex", "-interaction=nonstopmode", "-halt-on-error", path.name],
                   cwd=figure_dir, check=True, capture_output=True)
    for suffix in (".aux", ".log"):
        (figure_dir / f"{out_stem}{suffix}").unlink(missing_ok=True)
    print(f"{out_stem}: {note}")
    return height


if __name__ == "__main__":
    directory = HERE / sys.argv[1]
    build(directory, sys.argv[2], [list(r.split(",")) for r in sys.argv[3:]])
