"""Fig. 2c — direction-recovery forest plot aligned with Fig. 2b.

A small null-reference axis makes Pearson-delta = 0 visible, while a clearly
marked broken axis preserves enough horizontal resolution to compare the
0.54–0.66 confidence intervals. WT-null has no predicted direction and is
marked not defined.

Run: python fig2c_pearson_forest.py

Static QA contract: Arial; svg.fonttype: "none"; pdf.fonttype: 42; outputs
.svg, .pdf, .png and .tiff at dpi=600. Final assembled figure target:
width_mm = 183.
"""
from __future__ import annotations

import os
import sys
import csv

import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import nm_style as S
import remote_data as D

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fig2b_pds_forest import (AX_BOTTOM_MM, AX_HEIGHT_MM, ROW_YLIM,
                              add_row_bands, color_of, interval, row_layout)

HERE = os.path.dirname(os.path.abspath(__file__))
W_MM, H_MM = 44.0, 63.0
NULL_AX = (2.8, AX_BOTTOM_MM, 5.2, AX_HEIGHT_MM)
MAIN_AX = (10.7, AX_BOTTOM_MM, 31.6, AX_HEIGHT_MM)


def compute() -> dict[str, tuple[float, float, float, int]]:
    """Load the fixed-seed, 2,000-resample bootstrap summary.

    The source table is shipped with the panel so production rendering is
    deterministic and the plotted interval values remain directly auditable.
    """
    # Committed under results/, not beside the panel: the table is a derived
    # result and is regenerated by scripts/figures/make_pearson_bootstrap_summary.py
    # (seed 0, 2,000 percentile resamples), which also verifies it with --check.
    path = S.repo_root() / "results" / "pearson_delta_bootstrap_summary.csv"
    out = {}
    with open(path, newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            out[row["method"]] = (
                float(row["pearson_delta"]), float(row["ci_lo"]),
                float(row["ci_hi"]), int(row["n"]),
            )
    return out


def canvas():
    fig = plt.figure(figsize=(W_MM * S.MM, H_MM * S.MM))
    bg = fig.add_axes([0, 0, 1, 1])
    bg.set_axis_off()
    bg.set_xlim(0, 1)
    bg.set_ylim(0, 1)
    bg.add_patch(Rectangle((0, 0), 1, 1, facecolor="white",
                           edgecolor="none", zorder=-10))

    def add(rect):
        l, b, w, h = rect
        return fig.add_axes([l / W_MM, b / H_MM, w / W_MM, h / H_MM])

    return fig, add(NULL_AX), add(MAIN_AX)


def main() -> None:
    S.apply_rcparams()
    stats = compute()
    methods, ys = row_layout()
    pos = dict(zip(methods, ys))

    assert set(stats) == set(methods) - {"WT-null"}
    assert all(lo > 0 for _, lo, _, _ in stats.values())

    fig, ax0, ax = canvas()
    for axis in (ax0, ax):
        add_row_bands(axis)
        axis.set_ylim(*ROW_YLIM)
        axis.set_yticks(ys)
        axis.set_yticklabels([])
        axis.tick_params(axis="y", length=0)
        S.despine(axis, keep=("bottom",))

    # Explicit null anchor.
    ax0.set_xlim(-0.025, 0.075)
    ax0.set_xticks([0])
    ax0.set_xticklabels(["0"])
    ax0.axvline(0, color=S.INK, lw=0.6, ls=(0, (3, 2)), zorder=2)
    ax0.text(0, ROW_YLIM[1] - 0.12, "null", ha="center", va="top",
             fontsize=5.1, color=S.INK,
             bbox=dict(facecolor="white", edgecolor="none", pad=0.3), zorder=5)

    # Zoomed data range.
    ax.set_xlim(0.52, 0.68)
    ax.set_xticks([0.55, 0.60, 0.65])
    for method, y in zip(methods, ys):
        if method == "WT-null":
            continue
        mean, lo, hi, _ = stats[method]
        interval(ax, lo, hi, mean, y, color_of(method))

    ax.text(0.525, pos["WT-null"], "n.d.", ha="left", va="center",
            fontsize=5.2, color=S.GREY, fontstyle="italic")
    ax.tick_params(axis="x", pad=1.5)
    ax0.tick_params(axis="x", pad=1.5)

    # Conventional axis-break marks; drawn outside the data region.
    d = 0.018
    kwargs = dict(color=S.INK, clip_on=False, lw=0.55)
    ax0.plot((1 - d, 1 + d), (-d, +d), transform=ax0.transAxes, **kwargs)
    ax.plot((-d, +d), (-d, +d), transform=ax.transAxes, **kwargs)

    fig.text(0.60, 0.035, r"Pearson-$\delta$ (direction recovery)",
             ha="center", va="center", fontsize=7)
    fig.text(0.975, 0.925, "19/19 non-null CIs lie above 0",
             ha="right", va="center", fontsize=5.3,
             color=S.INK, fontstyle="italic")

    S.save(fig, os.path.join(HERE, "fig2c_pearson_forest"), exact=True,
           formats=("pdf", "png", "svg", "tiff"))


if __name__ == "__main__":
    main()
